### ISSUE TITLE
Cannot upload pandas df (create_from_dataframe)

### ISSUE THREAD

**Issue by tiems90** [Datatamer/tamr-client#311]
# 🐛 bug report

When following the instructions as listed [here](https://github.com/Datatamer/tamr-client/blob/aed16a553187354b1c59708ad87f0540383e67e7/docs/user-guide/spec.rst#creating-a-dataset) an error is thrown and the dataset is not created. 

## 🤔 Expected Behavior

Creation of a dataset from a pandas data frame. 

## 😯 Current Behavior

```
>>> dataset = client.datasets.create_from_dataframe(df, "col1", "My Data")
Traceback (most recent call last):
  File "/Users/timo/.pyenv/versions/3.6.5/envs/venv365/lib/python3.6/site-packages/tamr_unify_client/dataset/collection.py", line 164, in create_from_dataframe
    records, primary_key_name, ignore_nan=ignore_nan
  File "/Users/timo/.pyenv/versions/3.6.5/envs/venv365/lib/python3.6/site-packages/tamr_unify_client/dataset/resource.py", line 103, in upsert_records
    return self._update_records(updates, **json_args)
  File "/Users/timo/.pyenv/versions/3.6.5/envs/venv365/lib/python3.6/site-packages/tamr_unify_client/dataset/resource.py", line 81, in _update_records
    data=stringified_updates,
  File "/Users/timo/.pyenv/versions/3.6.5/envs/venv365/lib/python3.6/site-packages/tamr_unify_client/client.py", line 19, in successful
    self.raise_for_status()
  File "/Users/timo/.pyenv/versions/3.6.5/envs/venv365/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://10.20.0.228:9100/api/versioned/v1/datasets/175:updateRecords

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/timo/.pyenv/versions/3.6.5/envs/venv365/lib/python3.6/site-packages/tamr_unify_client/dataset/collection.py", line 167, in create_from_dataframe
    self._handle_creation_failure(dataset, "Records could not be created")
  File "/Users/timo/.pyenv/versions/3.6.5/envs/venv365/lib/python3.6/site-packages/tamr_unify_client/dataset/collection.py", line 187, in _handle_creation_failure
    raise CreationError(error)
tamr_unify_client.dataset.collection.CreationError: Records could not be created
```

## 💻 Code Sample

A basic self contained example, trying to upload a simple pandas df:

```
Python 3.6.5 (default, Oct 23 2019, 12:16:03)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
>>> import tamr_unify_client as api
>>> from tamr_unify_client.auth import UsernamePasswordAuth
>>> auth = UsernamePasswordAuth(XXXX)
>>> client = api.Client(auth, host=XXXX)
>>> client.projects.by_resource_id('1')
tamr_unify_client.project.resource.Project(relative_id='projects/1', name='Test_Categorization', type='CATEGORIZATION')
>>> df
   col1  col2
0     1     3
1     2     4
>>> dataset = client.datasets.create_from_dataframe(df, "col1", "My Data")
Traceback (most recent call last):
  File "/Users/timo/.pyenv/versions/3.6.5/envs/venv365/lib/python3.6/site-packages/tamr_unify_client/dataset/collection.py", line 164, in create_from_dataframe
    records, primary_key_name, ignore_nan=ignore_nan
  File "/Users/timo/.pyenv/versions/3.6.5/envs/venv365/lib/python3.6/site-packages/tamr_unify_client/dataset/resource.py", line 103, in upsert_records
    return self._update_records(updates, **json_args)
  File "/Users/timo/.pyenv/versions/3.6.5/envs/venv365/lib/python3.6/site-packages/tamr_unify_client/dataset/resource.py", line 81, in _update_records
    data=stringified_updates,
  File "/Users/timo/.pyenv/versions/3.6.5/envs/venv365/lib/python3.6/site-packages/tamr_unify_client/client.py", line 19, in successful
    self.raise_for_status()
  File "/Users/timo/.pyenv/versions/3.6.5/envs/venv365/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://10.20.0.228:9100/api/versioned/v1/datasets/175:updateRecords

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/timo/.pyenv/versions/3.6.5/envs/venv365/lib/python3.6/site-packages/tamr_unify_client/dataset/collection.py", line 167, in create_from_dataframe
    self._handle_creation_failure(dataset, "Records could not be created")
  File "/Users/timo/.pyenv/versions/3.6.5/envs/venv365/lib/python3.6/site-packages/tamr_unify_client/dataset/collection.py", line 187, in _handle_creation_failure
    raise CreationError(error)
tamr_unify_client.dataset.collection.CreationError: Records could not be created
```

## 🌍 Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| tamr-unify-client |  0.9.0
| Tamr server       |  2019.20
| Python            | 3.6.5
| Operating System  | MacOS/Ubuntu

**Comment by tiems90** [comment]
It failed as some fields were not formatted as text.
